[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@solmate/=lib/solmate/src/',
]

# set that the foundry will test the like putting random number 1000 times 
[fuzz]
runs = 1000
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
